"""Generate df64_constants.h: float32 hi/lo pairs of mathematical constants.

Run from the project root::

    .venv/bin/python Optiland-Metal/optiland/backend/torch_backend/metal/tools/\
        gen_df64_constants.py

Every value is computed with mpmath at 60 significant digits, split as
``hi = float32(v)``, ``lo = float32(v - hi)``, and checked to satisfy
``|lo| <= ulp(hi) / 2`` and ``|v - (hi + lo)| <= 2^-49 |v|``.
"""

from __future__ import annotations

import sys
from pathlib import Path

import mpmath
import numpy as np

mpmath.mp.dps = 60


def split(v: mpmath.mpf) -> tuple[np.float32, np.float32]:
    """Split an mpmath value into a normalized float32 pair."""
    hi = np.float32(float(v))
    lo = np.float32(float(v - mpmath.mpf(float(hi))))
    if hi != 0:
        ulp = np.spacing(np.abs(hi))
        assert abs(lo) <= ulp / 2 + 0, (v, hi, lo)
    err = abs(v - (mpmath.mpf(float(hi)) + mpmath.mpf(float(lo))))
    assert v == 0 or err <= mpmath.mpf(2) ** -49 * abs(v), (v, hi, lo, err)
    return hi, lo


def f32(x: np.float32) -> str:
    """Shortest round-trip float32 literal with an explicit f suffix."""
    text = f"{float(x):.9g}"
    if "." not in text and "e" not in text and "inf" not in text and "nan" not in text:
        text += ".0"
    return text + "f"


def emit(name: str, v: mpmath.mpf, comment: str = "") -> str:
    """Render one ``static constant df64`` line for ``v``."""
    hi, lo = split(v)
    c = f"  // {comment}" if comment else ""
    return f"static constant df64 {name} = {{{f32(hi)}, {f32(lo)}}};{c}"


def main() -> None:
    """Generate and write ``kernels/df64_constants.h``."""
    pi = mpmath.pi
    lines = [
        "// df64_constants.h — GENERATED by tools/gen_df64_constants.py. Do not edit.",
        "// Each constant is a normalized float32 pair (hi, lo) with |lo| <= ulp(hi)/2",
        "// and relative representation error <= 2^-49.",
        "#ifndef OPTILAND_DF64_CONSTANTS_H",
        "#define OPTILAND_DF64_CONSTANTS_H",
        "",
        "#pragma METAL fp math_mode(safe)",
        "#pragma METAL fp contract(off)",
        "",
        emit("DF64_PI", pi, "pi"),
        emit("DF64_2PI", 2 * pi, "2 pi"),
        emit("DF64_PI_2", pi / 2, "pi / 2"),
        emit("DF64_PI_4", pi / 4, "pi / 4"),
        emit("DF64_3PI_4", 3 * pi / 4, "3 pi / 4"),
        emit("DF64_PI_16", pi / 16, "pi / 16"),
        emit("DF64_1_PI", 1 / pi, "1 / pi"),
        emit("DF64_1_2PI", 1 / (2 * pi), "1 / (2 pi)"),
        emit("DF64_2_PI", 2 / pi, "2 / pi"),
        emit("DF64_LN2", mpmath.log(2), "ln 2"),
        emit("DF64_1_LN2", 1 / mpmath.log(2), "1 / ln 2 = log2(e)"),
        emit("DF64_LN10", mpmath.log(10), "ln 10"),
        emit("DF64_1_LN10", 1 / mpmath.log(10), "1 / ln 10 = log10(e)"),
        emit("DF64_E", mpmath.e, "e"),
        emit("DF64_SQRT2", mpmath.sqrt(2), "sqrt 2"),
        emit("DF64_1_SQRT2", 1 / mpmath.sqrt(2), "1 / sqrt 2"),
        emit("DF64_2_SQRTPI", 2 / mpmath.sqrt(pi), "2 / sqrt pi"),
        emit("DF64_SQRTPI", mpmath.sqrt(pi), "sqrt pi"),
        emit("DF64_LNPI", mpmath.log(pi), "ln pi"),
        emit("DF64_LN_SQRT2PI", mpmath.log(mpmath.sqrt(2 * pi)), "ln sqrt(2 pi)"),
        emit("DF64_EULER", mpmath.euler, "Euler-Mascheroni gamma"),
        "",
        "// Three-part pi/2 for Cody-Waite reduction:",
        "// PIO2_1 + PIO2_2 + PIO2_3 == pi/2 to ~72 bits. Each part has at most 12",
        "// significant bits so k * PIO2_i is exact in float32 for |k| < 2^12.",
    ]
    # 12-bit chunks of pi/2 as plain float32 constants
    v = pi / 2
    parts = []
    for _ in range(3):
        f = float(v)
        m, e = np.frexp(np.float32(f))
        chunk = np.float32(np.ldexp(np.floor(np.ldexp(float(m), 12)), e - 12))
        parts.append(chunk)
        v = v - mpmath.mpf(float(chunk))
    lines.append(f"static constant float DF64_PIO2_1 = {f32(parts[0])};")
    lines.append(f"static constant float DF64_PIO2_2 = {f32(parts[1])};")
    lines.append(f"static constant float DF64_PIO2_3 = {f32(parts[2])};")
    lines.append(emit("DF64_PIO2_REST", v, "remainder of pi/2 after the three chunks"))
    lines.append("")
    lines.append("// Inverse factorials 1/n! for n = 2..20 (index n).")
    lines.append("static constant df64 DF64_INV_FACT[21] = {")
    for n in range(21):
        hi, lo = split(mpmath.mpf(1) / mpmath.factorial(n))
        lines.append(f"    {{{f32(hi)}, {f32(lo)}}},  // 1/{n}!")
    lines.append("};")
    lines.append("")
    lines.append("// sin(k pi/16) and cos(k pi/16) for k = 0..4 (index k).")
    lines.append("static constant df64 DF64_SIN_TABLE[5] = {")
    for k in range(5):
        hi, lo = split(mpmath.sin(k * pi / 16))
        lines.append(f"    {{{f32(hi)}, {f32(lo)}}},  // sin({k} pi/16)")
    lines.append("};")
    lines.append("static constant df64 DF64_COS_TABLE[5] = {")
    for k in range(5):
        hi, lo = split(mpmath.cos(k * pi / 16))
        lines.append(f"    {{{f32(hi)}, {f32(lo)}}},  // cos({k} pi/16)")
    lines.append("};")
    lines.append("")
    lines.append("#endif  // OPTILAND_DF64_CONSTANTS_H")
    out = Path(__file__).resolve().parents[1] / "kernels" / "df64_constants.h"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    sys.exit(main())
