// df64_constants.h — GENERATED by tools/gen_df64_constants.py. Do not edit.
// Each constant is a normalized float32 pair (hi, lo) with |lo| <= ulp(hi)/2
// and relative representation error <= 2^-49.
#ifndef OPTILAND_DF64_CONSTANTS_H
#define OPTILAND_DF64_CONSTANTS_H

#pragma METAL fp math_mode(safe)
#pragma METAL fp contract(off)

static constant df64 DF64_PI = {3.14159274f, -8.74227766e-08f};  // pi
static constant df64 DF64_2PI = {6.28318548f, -1.74845553e-07f};  // 2 pi
static constant df64 DF64_PI_2 = {1.57079637f, -4.37113883e-08f};  // pi / 2
static constant df64 DF64_PI_4 = {0.785398185f, -2.18556941e-08f};  // pi / 4
static constant df64 DF64_3PI_4 = {2.3561945f, -5.96244032e-09f};  // 3 pi / 4
static constant df64 DF64_PI_16 = {0.196349546f, -5.46392354e-09f};  // pi / 16
static constant df64 DF64_1_PI = {0.318309873f, 1.28412765e-08f};  // 1 / pi
static constant df64 DF64_1_2PI = {0.159154937f, 6.42063824e-09f};  // 1 / (2 pi)
static constant df64 DF64_2_PI = {0.636619747f, 2.5682553e-08f};  // 2 / pi
static constant df64 DF64_LN2 = {0.693147182f, -1.90465421e-09f};  // ln 2
static constant df64 DF64_1_LN2 = {1.44269502f, 1.92596303e-08f};  // 1 / ln 2 = log2(e)
static constant df64 DF64_LN10 = {2.30258512f, -3.19754356e-08f};  // ln 10
static constant df64 DF64_1_LN10 = {0.434294492f, -1.010305e-08f};  // 1 / ln 10 = log10(e)
static constant df64 DF64_E = {2.71828175f, 8.25484037e-08f};  // e
static constant df64 DF64_SQRT2 = {1.41421354f, 2.4203235e-08f};  // sqrt 2
static constant df64 DF64_1_SQRT2 = {0.707106769f, 1.21016175e-08f};  // 1 / sqrt 2
static constant df64 DF64_2_SQRTPI = {1.12837923f, -5.86353828e-08f};  // 2 / sqrt pi
static constant df64 DF64_SQRTPI = {1.7724539f, -5.32463993e-08f};  // sqrt pi
static constant df64 DF64_LNPI = {1.14472985f, 3.31730092e-08f};  // ln pi
static constant df64 DF64_LN_SQRT2PI = {0.918938518f, 1.56341766e-08f};  // ln sqrt(2 pi)
static constant df64 DF64_EULER = {0.577215672f, -6.63777389e-09f};  // Euler-Mascheroni gamma

// Three-part pi/2 for Cody-Waite reduction:
// PIO2_1 + PIO2_2 + PIO2_3 == pi/2 to ~72 bits. Each part has at most 12
// significant bits so k * PIO2_i is exact in float32 for |k| < 2^12.
static constant float DF64_PIO2_1 = 1.5703125f;
static constant float DF64_PIO2_2 = 0.000483751297f;
static constant float DF64_PIO2_3 = 7.54953362e-08f;
static constant df64 DF64_PIO2_REST = {2.56334407e-12f, 8.33374321e-20f};  // remainder of pi/2 after the three chunks

// Inverse factorials 1/n! for n = 2..20 (index n).
static constant df64 DF64_INV_FACT[21] = {
    {1.0f, 0.0f},  // 1/0!
    {1.0f, 0.0f},  // 1/1!
    {0.5f, 0.0f},  // 1/2!
    {0.166666672f, -4.96705388e-09f},  // 1/3!
    {0.0416666679f, -1.24176347e-09f},  // 1/4!
    {0.00833333377f, -4.34617203e-10f},  // 1/5!
    {0.00138888892f, -3.36310944e-11f},  // 1/6!
    {0.000198412701f, -2.72559687e-12f},  // 1/7!
    {2.48015876e-05f, -3.40699609e-13f},  // 1/8!
    {2.75573188e-06f, 3.79357122e-14f},  // 1/9!
    {2.755732e-07f, -7.57511221e-15f},  // 1/10!
    {2.50521079e-08f, 4.41762304e-16f},  // 1/11!
    {2.08767559e-09f, 1.10828391e-16f},  // 1/12!
    {1.60590444e-10f, -5.35252651e-18f},  // 1/13!
    {1.14707454e-11f, 2.37220769e-19f},  // 1/14!
    {7.64716361e-13f, 1.22007105e-20f},  // 1/15!
    {4.77947726e-14f, 7.62544404e-22f},  // 1/16!
    {2.81145736e-15f, -1.04620847e-22f},  // 1/17!
    {1.56192068e-16f, 1.54044715e-24f},  // 1/18!
    {8.22063508e-18f, 1.6814781e-25f},  // 1/19!
    {4.11031759e-19f, 3.23751173e-27f},  // 1/20!
};

// sin(k pi/16) and cos(k pi/16) for k = 0..4 (index k).
static constant df64 DF64_SIN_TABLE[5] = {
    {0.0f, 0.0f},  // sin(0 pi/16)
    {0.195090324f, -1.67047143e-09f},  // sin(1 pi/16)
    {0.382683426f, 6.22335072e-09f},  // sin(2 pi/16)
    {0.555570245f, -1.17695214e-08f},  // sin(3 pi/16)
    {0.707106769f, 1.21016175e-08f},  // sin(4 pi/16)
};
static constant df64 DF64_COS_TABLE[5] = {
    {1.0f, 0.0f},  // cos(0 pi/16)
    {0.980785251f, 2.97394731e-08f},  // cos(1 pi/16)
    {0.923879504f, 2.83074897e-08f},  // cos(2 pi/16)
    {0.831469595f, 1.68702634e-08f},  // cos(3 pi/16)
    {0.707106769f, 1.21016175e-08f},  // cos(4 pi/16)
};

#endif  // OPTILAND_DF64_CONSTANTS_H
