// ---- elementwise kernels (GENERATED by codegen.py; do not edit) ----
#pragma METAL fp math_mode(safe)
#pragma METAL fp contract(off)

// ======== df64 (64 ops) ========
kernel void neg_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::neg(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void abs_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::abs(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sign_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::sign(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sqrt_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::sqrt(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void rsqrt_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::rsqrt(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void recip_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::recip(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void floor_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::floor(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void ceil_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::ceil(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void trunc_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::trunc(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void rint_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::rint(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void round_away_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::round_away(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void exp_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::exp(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void exp2_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::exp2(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void expm1_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::expm1(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void log_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::log(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void log1p_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::log1p(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void log2_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::log2(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void log10_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::log10(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void cbrt_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::cbrt(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sin_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::sin(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void cos_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::cos(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void tan_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::tan(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void asin_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::asin(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void acos_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::acos(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void atan_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::atan(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sinh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::sinh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void cosh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::cosh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void tanh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::tanh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void asinh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::asinh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void acosh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::acosh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void atanh_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::atanh(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void erf_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::erf(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void erfc_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::erfc(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void erfinv_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::erfinv(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void lgamma_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device float* o_hi [[buffer(2)]],
    device float* o_lo [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 r = df::lgamma(a);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void isnan_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    o[i] = df::is_nan(a);
}

kernel void isinf_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    o[i] = df::is_inf(a);
}

kernel void isfinite_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    o[i] = df::is_finite(a);
}

kernel void add_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::add(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void add_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::add(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void add_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::add(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sub_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::sub(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sub_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::sub(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void sub_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::sub(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void mul_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::mul(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void mul_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::mul(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void mul_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::mul(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void div_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::div(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void div_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::div(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void div_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::div(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmod_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmod(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmod_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::fmod(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmod_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmod(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void remainder_py_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::remainder_py(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void remainder_py_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::remainder_py(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void remainder_py_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::remainder_py(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void copysign_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::copysign(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void copysign_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::copysign(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void copysign_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::copysign(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void minimum_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::minimum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void minimum_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::minimum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void minimum_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::minimum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void maximum_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::maximum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void maximum_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::maximum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void maximum_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::maximum(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmin_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmin(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmin_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::fmin(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmin_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmin(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmax_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmax(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmax_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::fmax(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void fmax_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::fmax(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void pow_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::pow(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void pow_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::pow(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void pow_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::pow(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void atan2_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::atan2(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void atan2_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::atan2(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void atan2_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::atan2(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void hypot_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device float* o_hi [[buffer(4)]],
    device float* o_lo [[buffer(5)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::hypot(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void hypot_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    const df64 r = df::hypot(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void hypot_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device float* o_hi [[buffer(3)]],
    device float* o_lo [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 r = df::hypot(a, b);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void eq_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::eq(a, b);
}

kernel void eq_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::eq(a, b);
}

kernel void eq_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::eq(a, b);
}

kernel void ne_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::ne(a, b);
}

kernel void ne_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::ne(a, b);
}

kernel void ne_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::ne(a, b);
}

kernel void lt_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::lt(a, b);
}

kernel void lt_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::lt(a, b);
}

kernel void lt_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::lt(a, b);
}

kernel void le_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::le(a, b);
}

kernel void le_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::le(a, b);
}

kernel void le_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::le(a, b);
}

kernel void gt_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::gt(a, b);
}

kernel void gt_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::gt(a, b);
}

kernel void gt_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::gt(a, b);
}

kernel void ge_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device bool* o [[buffer(4)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::ge(a, b);
}

kernel void ge_df64_s(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    constant float2& b_s [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_s.x, b_s.y);
    o[i] = df::ge(a, b);
}

kernel void ge_df64_rs(
    constant float2& a_s [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device bool* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_s.x, a_s.y);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    o[i] = df::ge(a, b);
}

kernel void fma_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device const float* c_hi [[buffer(4)]],
    device const float* c_lo [[buffer(5)]],
    device float* o_hi [[buffer(6)]],
    device float* o_lo [[buffer(7)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = df::mul_add(a, b, c);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void lerp_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device const float* c_hi [[buffer(4)]],
    device const float* c_lo [[buffer(5)]],
    device float* o_hi [[buffer(6)]],
    device float* o_lo [[buffer(7)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = df::add(a, df::mul(c, df::sub(b, a)));
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void addcmul_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device const float* c_hi [[buffer(4)]],
    device const float* c_lo [[buffer(5)]],
    device float* o_hi [[buffer(6)]],
    device float* o_lo [[buffer(7)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = df::add(a, df::mul(b, c));
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void addcdiv_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device const float* c_hi [[buffer(4)]],
    device const float* c_lo [[buffer(5)]],
    device float* o_hi [[buffer(6)]],
    device float* o_lo [[buffer(7)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = df::add(a, df::div(b, c));
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void clamp_df64(
    device const float* a_hi [[buffer(0)]],
    device const float* a_lo [[buffer(1)]],
    device const float* b_hi [[buffer(2)]],
    device const float* b_lo [[buffer(3)]],
    device const float* c_hi [[buffer(4)]],
    device const float* c_lo [[buffer(5)]],
    device float* o_hi [[buffer(6)]],
    device float* o_lo [[buffer(7)]],
    uint i [[thread_position_in_grid]]) {
    const df64 a = df::make(a_hi[i], a_lo[i]);
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = df::minimum(df::maximum(a, b), c);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

kernel void where_df64(
    device const bool* a_mask [[buffer(0)]],
    device const float* b_hi [[buffer(1)]],
    device const float* b_lo [[buffer(2)]],
    device const float* c_hi [[buffer(3)]],
    device const float* c_lo [[buffer(4)]],
    device float* o_hi [[buffer(5)]],
    device float* o_lo [[buffer(6)]],
    uint i [[thread_position_in_grid]]) {
    const bool a = a_mask[i];
    const df64 b = df::make(b_hi[i], b_lo[i]);
    const df64 c = df::make(c_hi[i], c_lo[i]);
    const df64 r = (a ? b : c);
    o_hi[i] = r.hi;
    o_lo[i] = r.lo;
}

// ======== sf64 (64 ops) ========
// Bit-pattern <-> sf64 bridges used by every sf64 kernel. sf64 is a plain struct
// with a public `ulong bits` member (see sf64_core.h).
namespace ew {
inline sf64 sf_load(long v) { sf64 r; r.bits = as_type<ulong>(v); return r; }
inline long sf_store(sf64 v) { return as_type<long>(v.bits); }
}  // namespace ew

kernel void neg_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::neg(a));
}

kernel void abs_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::abs(a));
}

kernel void sign_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::sign(a));
}

kernel void sqrt_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::sqrt(a));
}

kernel void rsqrt_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::rsqrt(a));
}

kernel void recip_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::recip(a));
}

kernel void floor_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::floor(a));
}

kernel void ceil_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::ceil(a));
}

kernel void trunc_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::trunc(a));
}

kernel void rint_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::rint(a));
}

kernel void round_away_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::round_away(a));
}

kernel void exp_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::exp(a));
}

kernel void exp2_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::exp2(a));
}

kernel void expm1_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::expm1(a));
}

kernel void log_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::log(a));
}

kernel void log1p_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::log1p(a));
}

kernel void log2_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::log2(a));
}

kernel void log10_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::log10(a));
}

kernel void cbrt_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::cbrt(a));
}

kernel void sin_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::sin(a));
}

kernel void cos_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::cos(a));
}

kernel void tan_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::tan(a));
}

kernel void asin_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::asin(a));
}

kernel void acos_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::acos(a));
}

kernel void atan_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::atan(a));
}

kernel void sinh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::sinh(a));
}

kernel void cosh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::cosh(a));
}

kernel void tanh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::tanh(a));
}

kernel void asinh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::asinh(a));
}

kernel void acosh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::acosh(a));
}

kernel void atanh_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::atanh(a));
}

kernel void erf_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::erf(a));
}

kernel void erfc_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::erfc(a));
}

kernel void erfinv_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::erfinv(a));
}

kernel void lgamma_sf64(
    device const long* a_bits [[buffer(0)]],
    device long* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = ew::sf_store(sf::lgamma(a));
}

kernel void isnan_sf64(
    device const long* a_bits [[buffer(0)]],
    device bool* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = sf::is_nan(a);
}

kernel void isinf_sf64(
    device const long* a_bits [[buffer(0)]],
    device bool* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = sf::is_inf(a);
}

kernel void isfinite_sf64(
    device const long* a_bits [[buffer(0)]],
    device bool* o [[buffer(1)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    o[i] = sf::is_finite(a);
}

kernel void add_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::add(a, b));
}

kernel void add_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::add(a, b));
}

kernel void add_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::add(a, b));
}

kernel void sub_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::sub(a, b));
}

kernel void sub_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::sub(a, b));
}

kernel void sub_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::sub(a, b));
}

kernel void mul_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::mul(a, b));
}

kernel void mul_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::mul(a, b));
}

kernel void mul_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::mul(a, b));
}

kernel void div_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::div(a, b));
}

kernel void div_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::div(a, b));
}

kernel void div_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::div(a, b));
}

kernel void fmod_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmod(a, b));
}

kernel void fmod_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::fmod(a, b));
}

kernel void fmod_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmod(a, b));
}

kernel void remainder_py_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::remainder_py(a, b));
}

kernel void remainder_py_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::remainder_py(a, b));
}

kernel void remainder_py_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::remainder_py(a, b));
}

kernel void copysign_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::copysign(a, b));
}

kernel void copysign_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::copysign(a, b));
}

kernel void copysign_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::copysign(a, b));
}

kernel void minimum_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::minimum(a, b));
}

kernel void minimum_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::minimum(a, b));
}

kernel void minimum_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::minimum(a, b));
}

kernel void maximum_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::maximum(a, b));
}

kernel void maximum_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::maximum(a, b));
}

kernel void maximum_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::maximum(a, b));
}

kernel void fmin_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmin(a, b));
}

kernel void fmin_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::fmin(a, b));
}

kernel void fmin_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmin(a, b));
}

kernel void fmax_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmax(a, b));
}

kernel void fmax_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::fmax(a, b));
}

kernel void fmax_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::fmax(a, b));
}

kernel void pow_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::pow(a, b));
}

kernel void pow_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::pow(a, b));
}

kernel void pow_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::pow(a, b));
}

kernel void atan2_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::atan2(a, b));
}

kernel void atan2_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::atan2(a, b));
}

kernel void atan2_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::atan2(a, b));
}

kernel void hypot_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::hypot(a, b));
}

kernel void hypot_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = ew::sf_store(sf::hypot(a, b));
}

kernel void hypot_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device long* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = ew::sf_store(sf::hypot(a, b));
}

kernel void eq_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::eq(a, b);
}

kernel void eq_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::eq(a, b);
}

kernel void eq_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::eq(a, b);
}

kernel void ne_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::ne(a, b);
}

kernel void ne_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::ne(a, b);
}

kernel void ne_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::ne(a, b);
}

kernel void lt_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::lt(a, b);
}

kernel void lt_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::lt(a, b);
}

kernel void lt_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::lt(a, b);
}

kernel void le_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::le(a, b);
}

kernel void le_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::le(a, b);
}

kernel void le_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::le(a, b);
}

kernel void gt_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::gt(a, b);
}

kernel void gt_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::gt(a, b);
}

kernel void gt_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::gt(a, b);
}

kernel void ge_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::ge(a, b);
}

kernel void ge_sf64_s(
    device const long* a_bits [[buffer(0)]],
    constant long& b_s [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_s);
    o[i] = sf::ge(a, b);
}

kernel void ge_sf64_rs(
    constant long& a_s [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device bool* o [[buffer(2)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_s);
    const sf64 b = ew::sf_load(b_bits[i]);
    o[i] = sf::ge(a, b);
}

kernel void fma_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store(sf::fma(a, b, c));
}

kernel void lerp_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store(sf::add(a, sf::mul(c, sf::sub(b, a))));
}

kernel void addcmul_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store(sf::add(a, sf::mul(b, c)));
}

kernel void addcdiv_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store(sf::add(a, sf::div(b, c)));
}

kernel void clamp_sf64(
    device const long* a_bits [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const sf64 a = ew::sf_load(a_bits[i]);
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store(sf::minimum(sf::maximum(a, b), c));
}

kernel void where_sf64(
    device const bool* a_mask [[buffer(0)]],
    device const long* b_bits [[buffer(1)]],
    device const long* c_bits [[buffer(2)]],
    device long* o [[buffer(3)]],
    uint i [[thread_position_in_grid]]) {
    const bool a = a_mask[i];
    const sf64 b = ew::sf_load(b_bits[i]);
    const sf64 c = ew::sf_load(c_bits[i]);
    o[i] = ew::sf_store((a ? b : c));
}
