// Generated by metal/trace_layout.py -- do not edit.
// Regenerate with:
//   python -m optiland.backend.torch_backend.metal.trace_layout --write

#ifndef OPTILAND_TRACE_LAYOUT_H
#define OPTILAND_TRACE_LAYOUT_H

// launch planes (launch R[9][Lb][N])
#define OT_Q_X      0
#define OT_Q_Y      1
#define OT_Q_Z      2
#define OT_Q_L      3
#define OT_Q_M      4
#define OT_Q_N      5
#define OT_Q_I      6
#define OT_Q_OPD    7
#define OT_Q_W      8
#define OT_Q_PLANES 9

// final planes (final R[11][B][N])
#define OT_F_X      0
#define OT_F_Y      1
#define OT_F_Z      2
#define OT_F_L      3
#define OT_F_M      4
#define OT_F_N      5
#define OT_F_I      6
#define OT_F_OPD    7
#define OT_F_L0     8
#define OT_F_M0     9
#define OT_F_N0     10
#define OT_F_PLANES 11

// snapshot planes (snap R[8][B][n_rows][N])
#define OT_S_X      0
#define OT_S_Y      1
#define OT_S_Z      2
#define OT_S_L      3
#define OT_S_M      4
#define OT_S_N      5
#define OT_S_I      6
#define OT_S_OPD    7
#define OT_S_PLANES 8

// per-surface integer table (surf_int int32[B][S][SI_STRIDE])
#define OT_SI_GEOM     0
#define OT_SI_FLAGS    1
#define OT_SI_NCOEFF   2
#define OT_SI_MAXITER  3
#define OT_SI_APCODE   4
#define OT_SI_SNAPROW  5
#define OT_SI_STEPCOST 6
#define OT_SI_STRIDE   8

// geometry codes (SI_GEOM)
#define OT_GEOM_OBJECT  0
#define OT_GEOM_PLANE   1
#define OT_GEOM_STD_INF 2
#define OT_GEOM_CONIC   3
#define OT_GEOM_EVEN    4
#define OT_GEOM_ODD     5

// per-surface flag bits (SI_FLAGS)
#define OT_FL_HAS_RX       1
#define OT_FL_HAS_RY       2
#define OT_FL_HAS_RZ       4
#define OT_FL_REFLECTIVE   8
#define OT_FL_HAS_APERTURE 16
#define OT_FL_AP_IN_ROOT   32
#define OT_FL_ABSORBING    64
#define OT_FL_RADIUS_INF   128

// aperture codes (SI_APCODE)
#define OT_AP_NONE          0
#define OT_AP_RADIAL        1
#define OT_AP_OFFSET_RADIAL 2
#define OT_AP_RECT          3
#define OT_AP_ELLIPSE       4

// per-surface real table (surf_real R[B][S][SR_STRIDE])
#define OT_SR_TX     0
#define OT_SR_TY     1
#define OT_SR_TZ     2
#define OT_SR_NTX    3
#define OT_SR_NTY    4
#define OT_SR_NTZ    5
#define OT_SR_CNRZ   6
#define OT_SR_SNRZ   7
#define OT_SR_CNRY   8
#define OT_SR_SNRY   9
#define OT_SR_CNRX   10
#define OT_SR_SNRX   11
#define OT_SR_CRX    12
#define OT_SR_SRX    13
#define OT_SR_CRY    14
#define OT_SR_SRY    15
#define OT_SR_CRZ    16
#define OT_SR_SRZ    17
#define OT_SR_R      18
#define OT_SR_K      19
#define OT_SR_K1     20
#define OT_SR_R2     21
#define OT_SR_NPRE   22
#define OT_SR_NPOST  23
#define OT_SR_U      24
#define OT_SR_U2     25
#define OT_SR_ALPHA  26
#define OT_SR_TOL    27
#define OT_SR_AP0    28
#define OT_SR_AP1    29
#define OT_SR_AP2    30
#define OT_SR_AP3    31
#define OT_SR_STRIDE 32

// dimensions (dims int32[D_SIZE])
#define OT_D_S             0
#define OT_D_N             1
#define OT_D_B             2
#define OT_D_LAUNCH_STRIDE 3
#define OT_D_RAY_BASE      4
#define OT_D_NROWS         5
#define OT_D_C             6
#define OT_D_P             7
#define OT_D_DESIGN_BASE   8
#define OT_D_WRITE_FINAL   9
#define OT_D_SIZE          16

// kernel constants (consts R[C_SIZE])
#define OT_C_EPS    0
#define OT_C_NFLOOR 1
#define OT_C_SIZE   4

// status bits (status uint8[B][S][N])
#define OT_ST_MISS                 1
#define OT_ST_TIR                  2
#define OT_ST_CLIPPED              4
#define OT_ST_NEWTON_NOT_CONVERGED 8
#define OT_ST_TOL_CROSSOVER        16
#define OT_ST_NZ_FLOORED           32
#define OT_ST_DF_FLOORED           64
#define OT_ST_NONUNIFORM_W         128

// write-completion sentinel
#define OT_ITERS_UNWRITTEN 255

// positional binding order (argument order of every entry point)
// R-typed buffers bind as (hi, lo) in df64 and as one long in sf64;
// 16 bindings in df64, 10 in sf64.
// 0: launch (R)
// 1: surf_int (plain)
// 2: surf_real (R)
// 3: coef (R)
// 4: dims (plain)
// 5: consts (R)
// 6: snap (R)
// 7: final (R)
// 8: status (plain)
// 9: iters (plain)

#endif  // OPTILAND_TRACE_LAYOUT_H
