from collections.abc import Callable, Generator, Sequence  # noqa: I001
from contextlib import contextmanager
from typing import Any, Literal, TypeAlias

from numpy.random import Generator as NumpyGenerator
from numpy.typing import ArrayLike, NDArray
from torch import Generator as TorchGenerator
from torch import Tensor

from optiland._types import BEArrayT, ScalarOrArrayT
from optiland.backend.torch_backend.config import GradMode
from optiland.backend import linalg  # noqa: F401
from optiland.backend.base import BackendCapabilityError  # noqa: F401

__all__ = [
    "linalg",
    "BackendCapabilityError",
]

# ---------------------------------------------------------------------------
# Type alias — NDArray or Tensor, depending on the active backend
# ---------------------------------------------------------------------------

ndarray: TypeAlias = NDArray | Tensor  # noqa: PYI042

# ---------------------------------------------------------------------------
# Backend-independent constants
# ---------------------------------------------------------------------------

inf: float
nan: float
pi: float
e: float
newaxis: None
float32: type
float64: type
finfo: Any  # numpy.finfo — for machine-epsilon queries

# ---------------------------------------------------------------------------
# Backend management
# ---------------------------------------------------------------------------

def set_backend(name: str) -> None: ...
def get_backend() -> str: ...
def list_available_backends() -> list[str]: ...

# ---------------------------------------------------------------------------
# Torch-backend-only configuration
# ---------------------------------------------------------------------------

def set_device(device: Literal["cpu", "cuda"]) -> None: ...
def get_device() -> Literal["cpu", "cuda"]: ...
def set_precision(precision: Literal["float32", "float64"]) -> None: ...
def get_precision() -> Literal["float32", "float64"]: ...

grad_mode: GradMode

# ---------------------------------------------------------------------------
# Boolean queries
# ---------------------------------------------------------------------------

def array_equal(a: BEArrayT, b: BEArrayT) -> bool: ...
def allclose(
    a: BEArrayT, b: BEArrayT, rtol: float = 1e-5, atol: float = 1e-8
) -> bool: ...
def all(x: bool | ArrayLike) -> bool: ...
def any(x: bool | ArrayLike) -> bool: ...
def isinf(x: ScalarOrArrayT) -> ScalarOrArrayT: ...
def isnan(x: ScalarOrArrayT) -> ScalarOrArrayT: ...
def isfinite(x: ScalarOrArrayT) -> ScalarOrArrayT: ...
def isscalar(x: ArrayLike | ndarray) -> bool: ...
def is_array_like(x: Any) -> bool: ...

# ---------------------------------------------------------------------------
# Array creation — always return ndarray (new allocation)
# ---------------------------------------------------------------------------

def array(x: ArrayLike) -> ndarray: ...
def zeros(shape: Sequence[int]) -> ndarray: ...
def ones(shape: Sequence[int]) -> ndarray: ...
def full(shape: Sequence[int], fill_value: float) -> ndarray: ...
def zeros_like(x: ArrayLike) -> ndarray: ...
def ones_like(x: ArrayLike) -> ndarray: ...
def full_like(x: ArrayLike, fill_value: float) -> ndarray: ...
def empty(shape: Sequence[int]) -> ndarray: ...
def empty_like(x: ArrayLike) -> ndarray: ...
def eye(n: int) -> ndarray: ...
def linspace(start: float, stop: float, num: int) -> ndarray: ...
def arange(*args: float | ndarray, step: float | ndarray = 1) -> ndarray: ...
def arange_indices(start: Any, stop: Any = None, step: int = 1) -> ndarray: ...
def asarray(x: ArrayLike, **kwargs: Any) -> ndarray: ...
def load(filename: str) -> ndarray: ...
def cast(x: ArrayLike) -> ndarray: ...
def atleast_1d(x: ArrayLike) -> ndarray: ...
def atleast_2d(x: ArrayLike) -> ndarray: ...
def as_array_1d(data: ArrayLike) -> ndarray: ...

# ---------------------------------------------------------------------------
# Shape / structure — preserve the input array type
# ---------------------------------------------------------------------------

def shape(x: ArrayLike) -> tuple[int, ...]: ...
def size(x: ArrayLike) -> int: ...
def copy(x: BEArrayT) -> BEArrayT: ...
def ravel(x: BEArrayT) -> BEArrayT: ...
def reshape(x: BEArrayT, shape: Sequence[int]) -> BEArrayT: ...
def transpose(x: BEArrayT, axes: Sequence[int] | None = None) -> BEArrayT: ...
def expand_dims(x: BEArrayT, axis: int) -> BEArrayT: ...
def unsqueeze_last(x: BEArrayT) -> BEArrayT: ...
def broadcast_to(x: BEArrayT, shape: Sequence[int]) -> BEArrayT: ...
def repeat(x: BEArrayT, repeats: int) -> BEArrayT: ...
def flip(x: BEArrayT) -> BEArrayT: ...
def roll(
    x: BEArrayT, shift: int | Sequence[int], axis: int | tuple[int, ...] = ()
) -> BEArrayT: ...
def tile(x: BEArrayT, dims: int | Sequence[int]) -> BEArrayT: ...
def stack(xs: Sequence[ArrayLike], axis: int = 0) -> ndarray: ...
def concatenate(arrays: Sequence[BEArrayT], axis: int = 0) -> BEArrayT: ...
def vstack(xs: Sequence[BEArrayT]) -> BEArrayT: ...
def column_stack(xs: Sequence[BEArrayT]) -> BEArrayT: ...
def meshgrid(*arrays: BEArrayT) -> tuple[BEArrayT, ...]: ...

# ---------------------------------------------------------------------------
# Element-wise math — preserve the input array type
# ---------------------------------------------------------------------------

# Trigonometric
def sin(x: BEArrayT) -> BEArrayT: ...
def cos(x: BEArrayT) -> BEArrayT: ...
def tan(x: BEArrayT) -> BEArrayT: ...
def arcsin(x: BEArrayT) -> BEArrayT: ...
def arccos(x: BEArrayT) -> BEArrayT: ...
def arctan(x: BEArrayT) -> BEArrayT: ...
def arctan2(y: BEArrayT, x: BEArrayT) -> BEArrayT: ...
def sinh(x: BEArrayT) -> BEArrayT: ...
def cosh(x: BEArrayT) -> BEArrayT: ...
def tanh(x: BEArrayT) -> BEArrayT: ...

# Angle conversion
def radians(x: BEArrayT) -> BEArrayT: ...
def degrees(x: BEArrayT) -> BEArrayT: ...
def deg2rad(x: BEArrayT) -> BEArrayT: ...
def rad2deg(x: BEArrayT) -> BEArrayT: ...

# Exponential / logarithmic
def exp(x: BEArrayT) -> BEArrayT: ...
def log(x: BEArrayT) -> BEArrayT: ...
def log2(x: BEArrayT) -> BEArrayT: ...
def log10(x: BEArrayT) -> BEArrayT: ...

# Power / root
def sqrt(x: BEArrayT) -> BEArrayT: ...
def power(x: BEArrayT, y: BEArrayT) -> BEArrayT: ...
def hypot(x: BEArrayT, y: BEArrayT) -> BEArrayT: ...

# Rounding / sign
def abs(x: BEArrayT) -> BEArrayT: ...
def sign(x: BEArrayT) -> BEArrayT: ...
def floor(x: BEArrayT) -> BEArrayT: ...
def ceil(x: BEArrayT) -> BEArrayT: ...
def round(x: BEArrayT, decimals: int = 0) -> BEArrayT: ...
def copysign(x: BEArrayT, y: BEArrayT) -> BEArrayT: ...

# Binary element-wise comparisons
def maximum(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def minimum(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def fmax(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def isclose(
    a: BEArrayT, b: BEArrayT, rtol: float = 1e-5, atol: float = 1e-8
) -> BEArrayT: ...

# Logical element-wise
def logical_and(x: BEArrayT, y: BEArrayT) -> BEArrayT: ...
def logical_or(x: BEArrayT, y: BEArrayT) -> BEArrayT: ...
def logical_not(x: BEArrayT) -> BEArrayT: ...

# Complex
def conj(x: BEArrayT) -> BEArrayT: ...
def real(x: BEArrayT) -> BEArrayT: ...
def imag(x: BEArrayT) -> BEArrayT: ...
def to_complex(x: BEArrayT) -> BEArrayT: ...

# Differencing
def diff(x: BEArrayT, n: int = 1, axis: int = -1, **kwargs: Any) -> BEArrayT: ...

# Conditional selection
def where(condition: ArrayLike, x: ArrayLike, y: ArrayLike) -> ndarray: ...

# ---------------------------------------------------------------------------
# Reductions — return a scalar or reduced array
# ---------------------------------------------------------------------------

def sum(x: ArrayLike, axis: int | tuple[int, ...] | None = None) -> float: ...
def mean(x: ArrayLike, axis: int | None = None, keepdims: bool = False) -> ndarray: ...
def std(x: ArrayLike, axis: int | tuple[int, ...] | None = None) -> float: ...
def max(x: ArrayLike) -> int | float: ...
def min(x: ArrayLike) -> int | float: ...
def nanmax(x: ArrayLike, axis: int | None = None, keepdim: bool = False) -> ndarray: ...
def nansum(x: BEArrayT, axis: int | None = None) -> BEArrayT: ...
def nanmean(x: BEArrayT, axis: int | None = None) -> BEArrayT: ...
def sort(x: BEArrayT, axis: int = -1) -> BEArrayT: ...
def argmin(x: ArrayLike, axis: int | None = None) -> ndarray: ...
def argwhere(x: ArrayLike) -> ndarray: ...
def clip(x: BEArrayT, a_min: Any, a_max: Any) -> BEArrayT: ...
def searchsorted(a: BEArrayT, v: BEArrayT, side: str = "left") -> BEArrayT: ...
def factorial(n: ArrayLike) -> ndarray: ...

# ---------------------------------------------------------------------------
# Linear algebra
# ---------------------------------------------------------------------------

def matmul(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def batched_chain_matmul3(a: BEArrayT, b: BEArrayT, c: BEArrayT) -> BEArrayT: ...
def cross(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def outer(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def dot(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def einsum(subscripts: str, *operands: BEArrayT) -> BEArrayT: ...
def lstsq(a: BEArrayT, b: BEArrayT) -> BEArrayT: ...
def matrix_vector_multiply_and_squeeze(p: BEArrayT, E: BEArrayT) -> BEArrayT: ...
def mult_p_E(p: BEArrayT, E: BEArrayT) -> BEArrayT: ...

# ---------------------------------------------------------------------------
# Interpolation
# ---------------------------------------------------------------------------

def interp(x: ArrayLike, xp: ArrayLike, fp: ArrayLike) -> ndarray: ...
def nearest_nd_interpolator(
    points: BEArrayT, values: BEArrayT, Hx: BEArrayT, Hy: BEArrayT
) -> BEArrayT: ...
def grid_sample(
    input: BEArrayT,
    grid: BEArrayT,
    mode: str = "bilinear",
    padding_mode: str = "zeros",
    align_corners: bool = False,
) -> BEArrayT: ...

# ---------------------------------------------------------------------------
# Signal processing
# ---------------------------------------------------------------------------

def fftconvolve(
    in1: BEArrayT,
    in2: BEArrayT,
    mode: Literal["full", "valid", "same"] = "full",
) -> BEArrayT: ...

# ---------------------------------------------------------------------------
# Polynomial operations
# ---------------------------------------------------------------------------

def polyfit(x: BEArrayT, y: BEArrayT, degree: int) -> BEArrayT: ...
def polyval(coeffs: Sequence[float], x: float | ndarray) -> float | ndarray: ...

# ---------------------------------------------------------------------------
# Padding
# ---------------------------------------------------------------------------

def pad(
    x: BEArrayT,
    pad_width: int,
    mode: Literal["constant"] = "constant",
    constant_values: float | None = 0,
) -> BEArrayT: ...

# ---------------------------------------------------------------------------
# Vectorization
# ---------------------------------------------------------------------------

def vectorize(pyfunc: Callable[..., Any]) -> Callable[[ndarray], ndarray]: ...

# ---------------------------------------------------------------------------
# Random number generation
# ---------------------------------------------------------------------------

_Generator: TypeAlias = NumpyGenerator | TorchGenerator

def default_rng(seed: int | None = None) -> _Generator: ...
def rand(*size: int) -> ndarray: ...
def random_uniform(
    low: float = 0,
    high: float = 1,
    size: int | None = None,
    generator: _Generator | None = None,
) -> ndarray: ...
def random_normal(
    loc: float = 0,
    scale: float = 1,
    size: Sequence[int] | None = None,
    generator: _Generator | None = None,
) -> ndarray: ...
def sobol_sampler(
    dim: int,
    num_samples: int,
    scramble: bool = True,
    seed: int | None = None,
) -> ndarray: ...
def erfinv(x: ArrayLike) -> ndarray: ...

# ---------------------------------------------------------------------------
# Histograms
# ---------------------------------------------------------------------------

def histogram(x: BEArrayT, bins: int | BEArrayT = 10) -> tuple[BEArrayT, BEArrayT]: ...
def histogram2d(
    x: BEArrayT,
    y: BEArrayT,
    bins: Sequence[BEArrayT],
    weights: BEArrayT | None = None,
) -> tuple[BEArrayT, BEArrayT, BEArrayT]: ...
def get_bilinear_weights(
    coords: BEArrayT, bin_edges: Sequence[BEArrayT]
) -> tuple[BEArrayT, BEArrayT]: ...

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def copy_to(source: BEArrayT, destination: BEArrayT) -> None: ...
def path_contains_points(vertices: BEArrayT, points: BEArrayT) -> BEArrayT: ...
def to_numpy(obj: ArrayLike) -> NDArray: ...

# Error state context manager
@contextmanager
def errstate(**kwargs: Any) -> Generator[Any, Any, Any]: ...
