name: Publish to PyPI

permissions:
  contents: read

on:
  # Allow manual triggering
  workflow_dispatch:

  release:
    types: [released, prereleased]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/optiland

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-github:
    name: >-
      Publish Python distribution to GitHub Releases
    if: github.event_name == 'release'
    needs:
      - build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/
      - name: Upload wheels to GitHub release
        uses: svenstaro/upload-release-action@2.11.5
        with:
          tag: ${{ github.ref }}
          file: "dist/*.whl"
          file_glob: true
      - name: Upload dist to GitHub release
        uses: svenstaro/upload-release-action@2.11.5
        with:
          tag: ${{ github.ref }}
          file: "dist/*.tar.gz"
          file_glob: true
